# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49cfdea266258b95677859c9d3da3fce9b20b172ddb69ca7f9decf0ffe5976b9ff3f11565125caeb6fd36ed5e16e8a20af29aaabd01733d55197c29d27fc68b5

test:
  secret_key_base: 3f9d96067cb98aab9f7c2e2ae806b435bc1e529839b6de32c7e9011e4ab9624b1c92930db73edc060e7971dfb36b5aa0c9593f970e4a352b746e78012cc5aa73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
